parser: babel-eslint

env:
    node: true
    es6: true
    jest: true

plugins: [react]

extends: [eslint:recommended, plugin:import/errors, plugin:react/recommended]

rules:
  prefer-arrow-callback: error
  react/display-name: off
